### PR TITLE
FIX Remove incorrect modal close icon hover colour

### PR DESCRIPTION
**Pull request by sachajudd**
Closes: #548

cc @clarkepaul

### CODE REVIEW

**Comment by maxime-rainville** [comment]
Are the search button and close button to have different hover state?

screenshot from 2018-11-01 18-54-37
screenshot from 2018-11-01 18-52-29

**Comment by sachajudd** [comment]
We did discuss the close icon being more consistent with the other 'button like' hovers (such as search) but decided to just have a cursor change and no hover. I'll take another look at this.

**Comment by maxime-rainville** [comment]
I've rebased with 1. I'll merge on green.

**Comment by maxime-rainville** [comment]
Behat failure is unrelated. Merging.

**Pull request merged**
