### PR TITLE
FIX Display breadcrumb element from left to right

### PR DESCRIPTION
**Pull request by maxime-rainville**
Breadcrumb was going backwards.

I think the point of the reverse order was to try to cut off the higher level when there's not enough space to display the entire bread crumb.

This is what the new PR looks like when the breadcrumb gets cut off.
image

# Parent issue
* https://github.com/silverstripe/silverstripe-admin/issues/699

### CODE REVIEW

**Comment by maxime-rainville** [comment]
@clarkepaul This should fix our favourite issue.

**Comment by ScopeyNZ** [comment]
I think the overflow on the left hand side was intended as you're much more likely to want to know the highest level of the tree rather than the lowest when you're in a deeply nested folder.

**Comment by ScopeyNZ** [comment]
New issue raised here: https://github.com/silverstripe/silverstripe-admin/issues/930

**Comment by robbieaverill** [comment]
This change breaks the breadcrumbs in the "add new" screen of the CMS:

image

**Comment by ScopeyNZ** [comment]
That's not even React rendered right? So this is styles bleeding across different breadcrumb implementations? 😬

**Comment by robbieaverill** [comment]
Maybe. That happened with the search tag implementations in 4.2 as well, we need to ensure we name classes carefully!

**Comment by maxime-rainville** [comment]
https://github.com/silverstripe/silverstripe-admin/pull/942 should fix this

**Pull request merged**
