### PR TITLE
FIX PopoverOptionSet now explicitly sets an auto height for its search field

### LINKED ISSUE #792: PopoverOptionSet search field styling is broken
**Version: 4.x-dev**

See https://silverstripe.github.io/silverstripe-admin/?knob-Search=true&selectedKind=Admin%2FPopoverOptionSet&selectedStory=Custom%20Search&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

image

### PR DESCRIPTION
**Pull request by robbieaverill**
This fixes a bug where the inherited value from input styling renders it too small

Fixes https://github.com/dnadesign/silverstripe-elemental/issues/535 and fixes #792

### CODE REVIEW

**Comment by robbieaverill** [comment]
No I don’t know why, only checked that it is a regression

**Comment by robbieaverill** [comment]
Rebased

**Comment by robbieaverill** [comment]
Merging with two approvals after a straight rebase

**Comment by maxime-rainville** [comment]
Looks like the entire pattern lib is busted on IE11. I'll raise a separate issue.

**Pull request merged**
