### PR TITLE
ENH Make gridfield search options more accessible

### PR DESCRIPTION
**Pull request by GuySartorelli**
Add some text to the "advanced" specific search filter dropdown button.
This applies both for searching for pages and searching in a gridfield.

This is following UX advice that came up during the development of https://github.com/silverstripe/silverstripe-framework/pull/10382 - the intention being to make it clearer that there are additional search options (basically advanced search filters, usually, but theoretically these could be used to add arbitrary fields that can be used for arbitrary purposes in a custom `SearchContext`) available.

image

### CODE REVIEW

**Comment by emteknetnz** [comment]
@GuySartorelli could you rebase and rebuild bundle.js to resolve merge conflict please

**Comment by GuySartorelli** [comment]
Done.

**Comment by emteknetnz** [comment]
`git diff found modified files when it should not have:
D moment-locales/en-SG.js`

This sounds familiar, look at the history of this file to see if you get any clues

May need to use `git mv` if it's a filename capitilisation issue

**Comment by GuySartorelli** [comment]
Failing behat tests are unrelated - fixed in https://github.com/silverstripe/silverstripe-admin/pull/1336

**Review by emteknetnz — APPROVED** [review]
Approved, tested locally

**Before**
image


**After**
image

**Pull request merged**
