### PR TITLE
FIX TinyMCE custom config issue

### PR DESCRIPTION
**Pull request by sabina-talipova**
### Description
Renamed default skin from `lightgray` theme name to existing `silverstripe` theme if skin settings value is not defined. 
This solution won't work if passed skin name to the  editor settings is nonexistent directory. 

### Test instruction in installer

Modify ***app/_config.php***
```php
<?php

use SilverStripe\Security\PasswordValidator;
use SilverStripe\Security\Member;
use SilverStripe\Core\Manifest\ModuleLoader;
use SilverStripe\Forms\HTMLEditor\HTMLEditorConfig;

$validator = PasswordValidator::create();
Member::set_password_validator($validator);

// WYSIWYG editor config
$config = HTMLEditorConfig::get('cms');// use 'cwp' if installed with kitchen sink
$config->setOption('skin', null); 
```

### Parent issue
- https://github.com/silverstripe/silverstripe-admin/issues/1457

### CODE REVIEW

**Comment by sabina-talipova** [comment]
Close as wrong

**Comment by GuySartorelli** [comment]
I've updated the code snippet to be a much simpler setup for reproducing the original bug. This simply unsets the skin on all default WYSIWYG editors. No need to add new fields anywhere or define a whole new config. Jjust check the existing content field on a page, or inside elemental blocks, etc.

**Review by GuySartorelli — APPROVED** [review]
Nice and elegant! Works great locally in entwine and react contexts. Still allows a custom skin to be defined.

**Comment by GuySartorelli** [comment]
Tagged as [1.13.1](https://github.com/silverstripe/silverstripe-admin/releases/tag/1.13.1)

**Pull request merged**
