### PR TITLE
Logo updated to svg

### PR DESCRIPTION
**Pull request by clarkepaul**
Replaced the logo with SVG logo as it seemed that the retina image wasn't kicking in and only the low res one was being shown.

Shouldn't be any noticeable difference really except being clearer.
End result:
image

Tested in IE11, Chrome, with collapsed and open menu
Fixes https://github.com/silverstripe/silverstripe-admin/issues/321

### CODE REVIEW

**Comment by tractorcow** [comment]
@dhensby you merged it with the bug in it still...

**Comment by dhensby** [comment]
> @dhensby you merged it with the bug in it still...

Yep, I merged it 6 days before you pointed out the bug :( sorry I missed it

**Comment by tractorcow** [comment]
Lol I'm a dunce sorry. :)

**Comment by clarkepaul** [comment]
Cheers to whoever fixed it up, soz

**Pull request merged**
