### PR TITLE
FIX Revert vertically align form description contents

### PR DESCRIPTION
**Pull request by emteknetnz**
Fix for https://github.com/silverstripe/silverstripe-admin/issues/1090

Reverts https://github.com/silverstripe/silverstripe-admin/pull/1042/files

Travis behat failure is unrelated to this PR

image

### CODE REVIEW

**Review by dnsl48 — APPROVED** [review]

**Comment by dnsl48** [comment]
Looks good, but we need to figure out what's wrong with the tests before merging

**Comment by michalkleiner** [comment]
@dnsl48 can you trigger the tests again to see if it was something intermittent? We're upgrading some projects to latest recipes and having this fixed would be good.

**Comment by maxime-rainville** [comment]
@michalkleiner Behat failure should have been fixed by https://github.com/silverstripe/silverstripe-admin/pull/1114

I just restarted the tests.

**Comment by dnsl48** [comment]
Still failing. Restarting again :)

**Pull request merged**
