### PR TITLE
TLN Make `Search options` string translatable in `SearchBox.js`

### PR DESCRIPTION
**Pull request by pschiffe**
## Issues

- #1689

## Pull request checklist

- [x] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [x] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [x] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [x] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [x] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [x] This change is covered with tests (or tests aren't necessary for this change)
- [x] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [x] CI is green

### CODE REVIEW

**Comment by pschiffe** [comment]
This change will automatically get to the `2.1` branch, right?

**Comment by GuySartorelli** [comment]
> This change will automatically get to the `2.1` branch, right?
Yes, if this PR is merged in, the change will also be merged up to `1`, `2.1`, and `2`.

**Review by GuySartorelli — CHANGES_REQUESTED** [review]
Please also add this to the `client/lang/src/en.json` file, so that it can be added to the list in transifex.

**Comment by pschiffe** [comment]
> Please also add this to the `client/lang/src/en.json` file, so that it can be added to the list in transifex.

Done, thanks.

**Review by GuySartorelli — APPROVED** [review]
Awesome, thank you. I'll merge when CI goes green.

**Comment by GuySartorelli** [comment]
Oh yeah - changes to javascript require building the distribution files, which is why the JS CI build is failing.
Can you please give that a go? Instructions are at https://docs.silverstripe.org/en/contributing/build_tooling/ - if you get stuck I'm happy to help.

**Review by GuySartorelli — APPROVED** [review]
Fantastic, thanks for this. I'll merge when CI is green.

**Pull request merged**
