### PR TITLE
BUG Set min-width on loading button to avoid having the loading indicator break over 2 lines

### PR DESCRIPTION
**Pull request by maxime-rainville**
This give the loading indicator button a 

It's arguably a bit weird to have the [add] button suddenly get a bit wider when you click on it. But it's less weird than having it break over two lines with a broken animation. So I'm calling this an improvement.

I don't think we can apply a 70px min-width to all buttons, because that would probably end up making some button out of place that don't actually need the loading indicator.

# Parent issue
* https://github.com/silverstripe/silverstripe-admin/issues/862

### CODE REVIEW

**Comment by robbieaverill** [comment]
Does this work for batch action buttons?

**Comment by maxime-rainville** [comment]
Which batch action are we talking about? The CMS one and Asset-Admin one don't seem to be displaying any loading animation.

**Comment by robbieaverill** [comment]
Cool, yeah I meant the CMS ones

**Comment by maxime-rainville** [comment]
There's a really old bug open to do add some feedback when performing a batch CMS actions. Probably one of those thing that will need to wait until we migrate the sitetree UI to react. https://github.com/silverstripe/silverstripe-cms/issues/441

**Pull request merged**
