### PR TITLE
BUG Fix gridfield import modal

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes https://github.com/silverstripe/silverstripe-framework/issues/7162

### CODE REVIEW

**Comment by tractorcow** [comment]
Screenshot for context

image

**Comment by dhensby** [comment]
There are still improvements needed for this design.

"show specification for company" is just a hyperlink that doesn't imply it's to toggle visibility of text and it's grouped with the "replace data" checkbox which is unrelated.

see https://github.com/silverstripe/silverstripe-framework/issues/6431#issuecomment-312821427

**Comment by tractorcow** [comment]
Yes, but those improvements aren't the point of this PR. this is to fix the broken modal appearance, not complete the designs.

**Comment by flamerohr** [comment]
Lets get this working again first :)
I think there's a couple of design stories floating around for this modal alone

**Comment by tractorcow** [comment]
It looks like this is broken again.

**Comment by tractorcow** [comment]
image

**Pull request merged**
