### PR TITLE
BUG Do not override grid state with search parameters

### PR DESCRIPTION
**Pull request by maxime-rainville**
There's a bit of logic hat overrides the girdstate when you click the detail button with your search parameter, which might not reflect your current gridstate.

This video illustrate the original problem and the end results when the patch is applied.

https://youtu.be/Jw-zdpkXe-Q

# Parent issue
* https://github.com/silverstripe/silverstripe-admin/issues/886

### CODE REVIEW

**Comment by sminnee** [comment]
I think that we should get better about embedding grid state changes into the URL using the history js api

Benefits

* back button from a detail form goes back to the correct state
* copy/paste grid field URL goes to the state
* saving a multi-page editable gridfield returns to the right page

The main worry I would have is multiple grid fields on a single form, to check that the grid state is linked to the right grid.

I raise this here because I'm not sure if such work would conflict with this PR?

**Comment by maxime-rainville** [comment]
An alternative approach could be to make sure that any grid state change are immediately reflected in the URL. Even if we go with this kind of approach, I don't think we should directly read the GET parameters from the URL. We should have some sort of abstraction that can tell us what the current grid state is.

When you first access the a given URL, that abstraction would be hydrated with the grid state provided in the URL. Then has the grid sate changes, the abstraction would update the URL using the History JS API.

**Comment by sminnee** [comment]
> An alternative approach could be to make sure that any grid state change are immediately reflected in the URL

Sorry that's what I meant by "embedding grid state changes into the URL using the history js api"

I believe that with that in place, the server-side render of GridField should be able to do what's needed without special post-render treatment being needed in the JavaScript. At the very least, I would start by setting that theory using some handcrafted URLs.

I agree that the actual manipulation of the gridstate on the client side should be captured in a shared helper of some kind.

**Review by bergice — COMMENTED** [review]
I couldn't get this working.

When going back to the previous URL from the detail view, nothing is filtered and the query params are still empty.
When clicking the back button, the query params are present, but it's not filtering anything.

**Comment by maxime-rainville** [comment]
> When going back to the previous URL from the detail view, nothing is filtered and the query params are still empty.
When clicking the back button, the query params are present, but it's not filtering anything.

That's not exactly what this thing was trying to fix (although yes, we should fix that). 

The bug I was trying to fix is this.
- Access a ModalAdmin
- Sort by one column.
- Click on one entry. You'll be taken to the EditDetail form. Notice that when using "better-button" to navigate the result, the sorting order is honoured.
- Return to the list view.
- Sort by a different column.
- Click on one entry. Try navigating results using "better-button".

Expected results: The next result returns matches the second sorting order.
Actual results: The original sorting order selected is still used.

**Pull request merged**
