### PR TITLE
FIX Correct sizing of PopoverOptionSet, restore dismissal on blur

### LINKED ISSUE #1156: Popover (for Elemental) too narrow (1.7 regression)
The popover used for displaying available Elemental blocks appears to have become too narrow in 1.7 causing block names to become truncated.

**1.6**
Screenshot 2020-11-13 at 15 21 49@2x

**1.7**
Screenshot 2020-11-13 at 15 22 35@2x

Also, note the more obvious cut off top corners.

As per https://github.com/dnadesign/silverstripe-elemental/issues/848 I believe this is related to work done for the Reactstrap 8 upgrade. But unsure if resolving it is just a cause of increasing the new min-width: https://github.com/silverstripe/silverstripe-admin/blob/5d179b734ed1f97a0f3c853e29539e971c6988f5/client/src/components/PopoverOptionSet/PopoverOptionSet.scss#L15

## Acceptance Criteria
- This has been tested across a range of device sizes

### PR DESCRIPTION
**Pull request by Cheddam**
Fixes #1156.
Fixes dnadesign/silverstripe-elemental#876.

### CODE REVIEW

**Comment by kinglozzer** [comment]
This results in a min-width that’s larger than max-width again. To be honest, I’m not sure why we’re messing around with min/max widths at different breakpoints here - it looks to me like a much simpler problem than the existing CSS is making it.

`.popover` has a default `max-width: 276px` we need to override, but as far as I can see that’s pretty-much all we need to do:

```scss
$button-height: 40px;

.popover-option-set {
  display: flex;
  flex-direction: column;
  border-radius: $border-radius; // Change to equal 4px

  > .popover {
    width: calc(100% - 10px); // So the popover doesn't touch the edges of the viewport
    max-width: 450px;
  }
}
```

What do you think?

**Review by emteknetnz — APPROVED** [review]
I'd agree that it's backwards that we're essentially using `min-width` as `width`

On the other hand it seems like this PR works and it fixes a regression that was released on a non-stable tag, so, I'm keen to get this fixed.  The fix basically just reverts things to how the behaved previously, so this is fine IMO.

I've tested this in a few  browsers including IE11 and it looks fine

I'll approve though not merge @Cheddam if you're feeling inspired enough to change the usage of min-width/max-width to something a little more normal then I'm happy to test again, otherwise I'm happy for you to click the merge button yourself with the code as is

**Comment by emteknetnz** [comment]
@Cheddam somethings gone weird with it, it's lost the rounded corners at the top that was previously fixed in https://github.com/silverstripe/silverstripe-admin/pull/1176

image

**Comment by Cheddam** [comment]
@kinglozzer Thanks for weighing in!

I've adjusted the PR to reduce the number of properties used, in particular to remove conflicting min/max rules. However, I opted to keep the breakpoint in place, as removing it allowed the container to expand in width before the two-column mode kicked in, making that in-between stage look too wide.

I briefly removed the `overflow: hidden` property, not understanding its purpose, but have reinstated it as this was causing the border-radius issue @emteknetnz noted. The alternative solution to this issue would be to apply border-radius properties to the search / button container elements, but this feels more complex and brittle than simply retaining the overflow-based solution.

**Review by emteknetnz — APPROVED** [review]
Have tested latest update, including in IE11, works good

**Review by kinglozzer — APPROVED** [review]
Also tested, can confirm it fixes both bugs 👍

**Comment by kinglozzer** [comment]
Thanks @Cheddam!

**Pull request merged**
