### PR TITLE
Constrain reactstrap dependency for React v15

### PR DESCRIPTION
**Pull request by blueo**
reactstrap >=5.0.0-beta.3 drops support for react 15 and becomes 16 only. Beta 2 is the last tag before this changes.

I found this by checking up on the following console error:
```
__WEBPACK_IMPORTED_MODULE_5_react_dom___default.a.createPortal is not a function
    at Portal.render (reactstrap.es.js:3721)
```
as yarn included a later version of reactstrap

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
I think we should sneak this minor change into 1.3. In 1.4 we'll have React 16.

**Comment by robbieaverill** [comment]
Can we get the builds green?

**Comment by blueo** [comment]
yeah I wasn't 100% what this failure was: `The command "if [[ $NPM_TEST ]]; then git diff-files --quiet -w --relative=client; fi" exited with 1.` is this a diff on the vendor file? the next lines are:
```
$ if [[ $NPM_TEST ]]; then git diff --name-status --relative=client; fi
M	dist/js/vendor.js
```

**Comment by ScopeyNZ** [comment]
> yeah I wasn't 100% what this failure was: `The command "if [[ $NPM_TEST ]]; then git diff-files --quiet -w --relative=client; fi" exited with 1.` is this a diff on the vendor file? the next lines are:
> 
> ```
> $ if [[ $NPM_TEST ]]; then git diff --name-status --relative=client; fi
> M	dist/js/vendor.js
> ```

Yeah we commit the distribution (built) JS files. This test just confirms that the PR includes the bundles by compiling them itself and then running a `git diff-files`.

I'll update this for you.

**Comment by ScopeyNZ** [comment]
Hmmn there's a bunch of Behat failures now :\

**Comment by maxime-rainville** [comment]
I've rebased the PR.

**Comment by robbieaverill** [comment]
Rebased again

**Comment by robbieaverill** [comment]
The behat failures are potentially relevant. I'll re-run them just in case.

**Comment by Cheddam** [comment]
Sorry this didn't make it across the line, @blueo! Since the [4.3 line is EOL now](https://www.silverstripe.org/software/roadmap/), and later CMS releases have adopted React 16, I'll close this out.

**Pull request closed without merging**
