### PR TITLE
NEW Add --inverted modifier for Badge component with pattern library examples

### PR DESCRIPTION
**Pull request by robbieaverill**
This adds inverted colour states via a tweaked mixin copied through from Bootstrap. I've updated the pattern library to show the different states in different sections.

Required for https://github.com/silverstripe/silverstripe-versioned/issues/104

Pattern library screenshots:

image

image

image

This is to allow more badge contexts, for example when being displayed against a darker background:

image

### CODE REVIEW

**Comment by robbieaverill** [comment]
Thanks @raissanorth! If it helps, the SCSS is copy and pasted from Bootstrap's source code with the assignments for `color` and `background-color` switched around - see cited code:

* https://github.com/twbs/bootstrap/blob/v4.0.0/scss/_badge.scss#L39-L46
* https://github.com/twbs/bootstrap/blob/v4.0.0/scss/mixins/_badge.scss

**Comment by tractorcow** [comment]
Just needs a rebase.

**Comment by robbieaverill** [comment]
Rebased :)

**Comment by tractorcow** [comment]
PR to fix this crash at https://github.com/silverstripe/silverstripe-framework/pull/7989

**Pull request merged**
