### PR TITLE
FIX JS Console errors and warnings

### PR DESCRIPTION
**Pull request by sabina-talipova**
## Description
`SearchableDropdownField` was tested with LinkField, Elemental and simply on a Page. There are not any related errors or warnings in dev or prod.

## Parent issue
- https://github.com/silverstripe/silverstripe-admin/issues/1690

### CODE REVIEW

**Comment by sabina-talipova** [comment]
> There is still no formfield displaying. A field should be displayed (that's the main thing the issue is about - the console errors were just added to help diagnose what's causing the problem).

@GuySartorelli, I fixed it CMS 5.x-dev version (new env) and tested in different objects like Page, LinkField(FileLink) or Elemental. Everywhere I can create, save and update.

Screenshot 2024-03-05 at 11 01 42 AM

**Comment by GuySartorelli** [comment]
Are you checking inside a modal, as per the reproduction steps in the issue?
[Screencast from 05-03-24 16:44:43.webm](https://github.com/silverstripe/silverstripe-admin/assets/36352093/374b76d5-9e37-43ea-af54-2a867e3e7fea)

**Comment by sabina-talipova** [comment]
Thank you for the video. It helped.
Ha, but we are talking about two different fields. You show me issue with `TreeDropdownField` and I fixed some issues in `SearchableDropdownField`.  If you click on "Details" you can work with fields, but by default (I don't know why?) this modal form is in read only state.
Probably, we should update styles for read only fields if they don't have a content.

https://github.com/silverstripe/silverstripe-admin/assets/87288324/741bafa1-20de-426a-8a52-765bb25a9869

**Comment by GuySartorelli** [comment]
Ahh, oops! The issue was meant to be about the fields I pointed at. I incorrectly identified them as `SearchableDropdownField` but turns out I was wrong.


I'll merge this since it resolves the console errors.
I'll leave it up to you to decide whether to close the attached issue and raise a separate one about `TreeDropdownField` not displaying, or whether you want to work on that as part of the existing issue.

**Review by GuySartorelli — APPROVED** [review]

**Pull request merged**
