### PR TITLE
FIX Collapse the preview panel by default if no preview is available.

### PR DESCRIPTION
**Pull request by GuySartorelli**
This makes the editor experience more streamlined for DataObjects that _can_ have a preview (and therefore the preview panel is present) but do not have a preview in the current context (e.g. an elemental block owned by a non-previewable DataObject).

## Dependencies (won't work without these PRs)
- silverstripe/silverstripe-cms#2737

## Parent issue
- #1304

### CODE REVIEW

**Comment by michalkleiner** [comment]
Should it be collapsed or disabled? Sorry been a while for me — what happens when you open the panel and there's no preview available? Is there a 'No preview available' state? All good if that's already the case.

**Comment by GuySartorelli** [comment]
> what happens when you open the panel and there's no preview available? Is there a 'No preview available' state?

Yup! Theoretically at least. There's a related PR to this in the description that makes sure null or empty preview links will display the "no preview available" message. Unfortunately the classes that handle that are in CMS... we should move them to admin at some point.

> Should it be collapsed or disabled?

I think it should be collapsed - the "no preview" message will display if users choose to expand it. This reflects the fact that the data object _is_ previewable, there's just no preview for it in the current context.
That said, I'm not a UX expert by any means... if anyone has reasoning why it should be disabled I'm happy to make that change.

**Comment by GuySartorelli** [comment]
Changed base from `1` to `1.11` as this is a fix that should be included in the 1.11.0 release.

**Comment by GuySartorelli** [comment]
I've created an issue (#1306 ) for adding test coverage for previews in admin - there currently aren't any in admin itself, so it will be quite a big task that I won't be able to get done in the current sprint.

**Review by sabina-talipova — APPROVED** [review]

**Pull request merged**
