### PR TITLE
FIX Set min-width of popover

### PR DESCRIPTION
**Pull request by emteknetnz**
Fixes https://github.com/silverstripe/silverstripe-admin/issues/1156

### CODE REVIEW

**Comment by kinglozzer** [comment]
This does make the dropdown slightly wider, but I’m not sure it’s the best fix as it’s still much narrower than it was before the bug was introduced.

`.popover` still has a `max-width: 276px;` rule (from Reactstrap I think) so we’re in the slightly muddy waters of setting a `min-width` and `max-width` that conflict. Would we be better served by just updating the `max-width` instead?

```scss
  > .popover {
    min-width: 280px;
    max-width: $column-width * 2;
  }
```

**Review by maxime-rainville — CHANGES_REQUESTED** [review]
What @kinglozzer said.

Looking at 1.6, these are the `max-width` at different breakpoints:
- 280px by default
- 450px with for displays 544px or wider

**Comment by emteknetnz** [comment]
I've updated the CSS

**Review by maxime-rainville — APPROVED** [review]
It doesn't quite look the same way it did in 1.6, but it meets my smelly developer standards.

I tested in Firefox, Chrome and IE11. I did notice that the border radius appears more pronounce in 1.7 than in 1.6.

If @clarkepaul approves, I'm fine with merging.

This video shows what it looks like: https://youtu.be/19Zvsanr7Fw
- Right tab is plain 1.6
- Left tab is 1.7 with the PR

**Comment by clarkepaul** [comment]
I'm fine with that cheers, happy for a merge from my side. FYI in the original designs we didn't specify widths but we designed it at 320px wide to accommodate mobile devices. I'm happy that it's ended up being slightly wider for desktop as people seem to favour long block names.
[Design reference](https://projects.invisionapp.com/share/N5MVKR392DS#/screens/318343221_Add_Block)

**Review by maxime-rainville — APPROVED** [review]
Everyone is happy

**Comment by thats4shaw** [comment]
The addition of a max width of 100% seems to cause something like this:
Screen Shot 2021-02-16 at 4 48 17 PM

```
dnadesign/silverstripe-elemental 4.5.0
silverstripe/admin 1.7.2 
```

**Comment by maxime-rainville** [comment]
@thats4shaw I've reopen the parent issue. Can you let us know what browser you are using?
https://github.com/silverstripe/silverstripe-admin/issues/1156

**Pull request merged**
