### PR TITLE
Fix field type not displaying on userform

### PR DESCRIPTION
**Pull request by bergice**
Resolves https://github.com/silverstripe/silverstripe-userforms/issues/874

### CODE REVIEW

**Review by maxime-rainville — COMMENTED** [review]
Couldn't we fix this in userform specifically? Seems like this could have impacts in other part of the CMS.

**Comment by bergice** [comment]
> Couldn't we fix this in userform specifically? Seems like this could have impacts in other part of the CMS.

We could, but we'd need to add bootstrap to userforms.

**Comment by maxime-rainville** [comment]
You can probably get away with adding a more specific CSS selector to [userforms-cms.scss](https://github.com/silverstripe/silverstripe-userforms/blob/5/client/src/styles/userforms-cms.scss) to override the admin rule.

**Comment by emteknetnz** [comment]
As Max has suggested, recommend that you open a PR on userforms and update https://github.com/silverstripe/silverstripe-userforms/blob/5/client/src/styles/userforms-cms.scss

**Pull request closed without merging**
