### PR TITLE
Ignore "load" statusText

### LINKED ISSUE #1428: 1.12 model admin show random "load" notification (with CDNs specifically)
Not sure exactly why, but this is happening since I upgraded to 1.12.

If I navigate from a Model Admin screen to a record, I get this

image

It only happens for some type of records, not all I've tried to trim down the fields to see if there is anything specific, but no luck so far.

it only happens the first time I load a record, after that, no more notification (i can go back to the list, load another one, etc...)

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1429 (CMS 4)
- https://github.com/silverstripe/silverstripe-admin/pull/1444 (CMS 5)

### PR DESCRIPTION
**Pull request by lekoala**
Fixes https://github.com/silverstripe/silverstripe-admin/issues/1428

### CODE REVIEW

**Comment by GuySartorelli** [comment]
In the issue you've indicated that the "load" text is coming from a cdn - I don't think that the core codebase should cater to specific cdn messages. Rather, I think it would make sense to make this configurable somehow so that developers can mark specific messages to be ignored based on their specific requirements.

**Comment by lozcalver** [comment]
This is an odd one, HTTP status text can be _anything_ so maintaining a whitelist like this doesn’t really make sense. How about we adjust this code so that we use the `X-Status` header, but only fall back to using the HTTP status text if the response code is not 2xx?

The correct way for devs to show messages is to use the `X-Status` header so I don’t see a BC risk, I’m not even sure if manually setting HTTP status text is possible? IIRC the webserver will override it anyway based on response code

**Comment by lekoala** [comment]
> In the issue you've indicated that the "load" text is coming from a cdn - I don't think that the core codebase should cater to specific cdn messages. Rather, I think it would make sense to make this configurable somehow so that developers can mark specific messages to be ignored based on their specific requirements.

@GuySartorelli  it's not specific from that given cdn, but any cdn. From what I understand, any load event from an outside server will get that statusText, so it's pretty generic

as @kinglozzer said, I don't think it's a good idea at all to display generic statusText anyway (except maybe for 4xx and 5xx statuses) and only display X-Status and get rid of the ignoredMessages.

My PR wasn't meant to address the broader issue :-)

**Comment by lozcalver** [comment]
I’ve created a PR with the alternative approach https://github.com/silverstripe/silverstripe-admin/pull/1444

**Comment by GuySartorelli** [comment]
Closed in favour of #1444

**Comment by GuySartorelli** [comment]
Reopened as the alternate solution is a breaking change.
I still think it would be best to have this be configurable.... but I can't think off the top of my head how to do that so maybe this fix is okay as is? Thoughts @silverstripe/core-team ?

**Comment by michalkleiner** [comment]
Seems like we don't have an established way of passing config data from PHP config manifest to JS via e.g. a data attribute on `body` or a separate script tag (or one that I could easily find), and it would probably be an overkill for this anyway, so I'd be happy to accept this as is for now, and resolve the X-Status message in CMS 5.

**Review by michalkleiner — APPROVED** [review]

**Comment by GuySartorelli** [comment]
@lekoala please run `yarn install && yarn build` and commit the dist changes.

**Comment by lekoala** [comment]
@GuySartorelli this is actually not as easy as it looks

i'm using yarn 2 and node 16 on my local machine. sure, i can switch node with nvm, and set policies to use yarn v1, but it still updates a bunch of values as well (eg: adding a packageManager entry in package.json, creating a yarnrc file)
yarn install throw a bunch of warnings as well (but seems to work more or less)
yarn build fails on this
$ eslint client/src && sass-lint -v
The system cannot find the path specified.
(probably a windows thing)

^^ not exactly sure what's going on and not sure i want to spend more time on this. one thing for certain, build tooling in Silverstripe is not very friendly for developers that don't use them on a daily basis.

soo... probably better if someone else gives this a go :-)
it would be great of there was some automated ci thing that would build dist files automatically, that would make contributing much easier
i know for my part that most of my fixes are applied directly on prod files (not great, i know, but at least i can test things in a real environment without having to setup a whole thing just to change one line of js)

**Comment by michalkleiner** [comment]
Getting the same error with the lint when trying to run `yarn build` on a Mac.

```
 ~/github/silverstripe-admin   patch-4±  yarn build
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @storybook/addon-knobs@npm:3.4.12 [af7e5] doesn't provide react-dom (pa8567), requested by @storybook/components
➤ YN0002: │ @storybook/addon-knobs@npm:3.4.12 [af7e5] doesn't provide react-dom (p667fb), requested by react-datetime
➤ YN0002: │ @storybook/mantra-core@npm:1.7.2 doesn't provide react (pd4f0d), requested by @storybook/react-komposer
➤ YN0002: │ @storybook/mantra-core@npm:1.7.2 doesn't provide react (p379d9), requested by @storybook/react-simple-di
➤ YN0002: │ apollo-link-batch@npm:1.1.15 doesn't provide graphql (pad667), requested by apollo-link
➤ YN0002: │ apollo-link-error@npm:1.1.13 doesn't provide graphql (p17213), requested by apollo-link
➤ YN0002: │ apollo-link-error@npm:1.1.13 doesn't provide graphql (pbcdcb), requested by apollo-link-http-common
➤ YN0002: │ apollo-link-state@npm:0.4.2 [af7e5] doesn't provide graphql (p1111c), requested by graphql-anywhere
➤ YN0002: │ react-icons@npm:2.2.7 [adc63] doesn't provide prop-types (p4908a), requested by react-icon-base
➤ YN0002: │ silverstripe-admin@workspace:. doesn't provide babel-core (p37402), requested by @storybook/react
➤ YN0002: │ silverstripe-admin@workspace:. doesn't provide babel-core (pbb76a), requested by babel-jest
➤ YN0002: │ silverstripe-admin@workspace:. doesn't provide babel-core (p111f1), requested by storybook-addon-jsx
➤ YN0002: │ silverstripe-admin@workspace:. doesn't provide node-sass (pc7f12), requested by sass-loader
➤ YN0060: │ silverstripe-admin@workspace:. provides react-router (pf15f0) with version 4.4.0-beta.8, which doesn't satisfy what react-router-config requests
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 461ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 570ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 1s 18ms
➤ YN0000: Done with warnings in 2s 445ms
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/Users/michalkleiner/github/silverstripe-admin/node_modules/@silverstripe/eslint-config/node_modules/.bin/eslint'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by michalkleiner** [comment]
Ok, rebased the patch branch on top of `1` and ran `yarn install && yarn build` (using Node 10.20.1 and Yarn 1.19.22).

**Comment by michalkleiner** [comment]
I'd also like to see if you arrive at the same dist JS file @GuySartorelli.

**Comment by GuySartorelli** [comment]
Ran `yarn install && yarn build` locally and got a different result, so I've pushed that.
In case it's useful/relevant:
```bash
$ node -v
v10.24.1

$ yarn -v
1.22.18
```

**Comment by GuySartorelli** [comment]
CI is happy with that.
@michalkleiner if you're good with this, I'm happy for it to be merged.

**Comment by michalkleiner** [comment]
Yep, I'll try with those versions as well but I suspect I will still get a different result which is slightly weird but not worth spending time on at this stage.

Go for merge @GuySartorelli

**Review by GuySartorelli — APPROVED** [review]

**Comment by GuySartorelli** [comment]
Thanks @lekoala

**Pull request merged**
