### PR TITLE
Fix toggle rendering

### PR DESCRIPTION
**Pull request by bergice**
Chrome has a bug when rendering small circles (`border-radius: 50%`). This change fixes that for the toggle button on the bottom left of the screen.

Before:
image

After:
image

### CODE REVIEW

**Review by maxime-rainville — CHANGES_REQUESTED** [review]
Didn't manage to replicate this issue in CMS `4.6.x-dev` with Chrome `87.0.4280.66`. Can you confirm this is still an issue?

**Comment by bergice** [comment]
> Didn't manage to replicate this issue in CMS `4.6.x-dev` with Chrome `87.0.4280.66`. Can you confirm this is still an issue?

Just tested again and I'm pretty sure this is only an issue when zooming the page: 
image

**Comment by maxime-rainville** [comment]
I see it when I zoom-out to 90%. When I zoom-in it looks OK.

The fix does slightly alter the look of the radio button. IF @silverstripeux is happy with it, we can merge.

# Current
image

# With PR
image

**Comment by sachajudd** [comment]
I don't see how changing the width and height would fix the problem. At 90% it's still going to break with this change, and actually look worse IMO.
image

**Comment by michalkleiner** [comment]
It's also weirdly a button with a radio-like indicator — should it rather be a true checkbox since it only has two states toggling a single setting?

**Comment by maxime-rainville** [comment]
@bergice Do you want to have another crack at this or should we close this PR?

**Pull request closed without merging**
