### PR TITLE
Update font icons

### PR DESCRIPTION
**Pull request by sachajudd**
Updated icon screen shot 2009-12-26 at 5 25 51 pm

### CODE REVIEW

**Comment by dhensby** [comment]
The NPM build sanity checks have failed :(

**Comment by sachajudd** [comment]
I'll take another look at this on Monday 🙂

**Comment by tractorcow** [comment]
It looks as though this changes removes a recently added font icon, too.

**Comment by tractorcow** [comment]
Ok, I've investigated the issue with the missing icon. It looks like it was renamed incorrectly, but the damage is done now, so I think we can just leave it as is for now.

**Pull request merged**
