### PR TITLE
Adding TS support to admin with webpack

### PR DESCRIPTION
**Pull request by maxime-rainville**
This supersede https://github.com/silverstripe/silverstripe-admin/pull/828. It's got a better build logic with webpack. I've recorded some videos that explains how and why we should start using TypeScript in our project

* [High level overview of the benefit of TS](https://youtu.be/PXb-K9wTAbc) (23 min)
* [How the SilverStripe TS implementation works](https://youtu.be/bd5Gm6faI3s) (10 min)

_If you click the gear icon on youtube, you can speed up the video_

### CODE REVIEW

**Comment by maxime-rainville** [comment]
Grrr ... `expose-loader` is being difficult. Need to sort it out.

**Comment by chillu** [comment]
Woop woop! I'm assuming you're still writing up an RFC on why we should add TS, and how that's impacting our workflow and contributions?

**Comment by maxime-rainville** [comment]
I can provide more textual summary, but the video were meant to demonstrate that's super easy to get everything working. I don't really see this as a big change to our workflow. It's just a question of learning a few extra keywords. I was planning to do a third video demonstrating how to get an admin dependant module working when I ran into the `expose-loader` issue. I'll try to get that wrapped up before our next dev architectural catch up so I can demo it.

**Comment by maxime-rainville** [comment]
We had discussion about this internally and decided it wasn't achievable in the current release line.

**Pull request closed without merging**
