### PR TITLE
Replace logo with font icon logo

### PR DESCRIPTION
**Pull request by clarkepaul**
Replaced the logo with SVG logo as it seemed that the retina image wasn't kicking in and only the low res one was being shown.

Shouldn't be any noticeable difference really except being clearer.
End result:
image

Tested in IE11, Chrome, with collapsed and open menu

### CODE REVIEW

**Comment by clarkepaul** [comment]
Fixes https://github.com/silverstripe/silverstripe-admin/issues/321

**Comment by clarkepaul** [comment]
@unclecheese did I request this for the wrong branch? I'm not seeing the change in the latest code base.

**Comment by clarkepaul** [comment]
@unclecheese Looks like it's in branch 1 but I presume we made the switch to 1.0 about the same time, should I create another PR?

**Comment by dhensby** [comment]
> should I create another PR?

please

**Comment by clarkepaul** [comment]
New PR here https://github.com/silverstripe/silverstripe-admin/pull/361

**Pull request merged**
