### PR TITLE
FIX Move toast notification so that tabs behind it are clickable

### PR DESCRIPTION
**Pull request by emteknetnz**
Fix for https://github.com/silverstripe/silverstripe-admin/issues/1018

Before
image

After
image

### CODE REVIEW

**Comment by emteknetnz** [comment]
@clarkepaul based on your [comment](https://github.com/silverstripe/silverstripe-admin/issues/1018#issuecomment-674576359) in the parent issue - is this still something you want to be merged

**Comment by clarkepaul** [comment]
Yes please. People have requested it, that mention I made of moving tabs isn't going to happen anytime soon.

**Review by bergice — COMMENTED** [review]
From a code point of view this looks OK.

However, I'm inclined to agree with @michalkleiner that it makes assumptions that the toast will always be displayed on a page with the navbar present:

> I'm no UX expert but I feel like the position of the notification shouldn't care about what it overlays if it's related to the whole CMS window. Moving it down below the tabs nav makes it seem nested inside the content tab area, not 'top-level', if you know what I mean.

Will let @clarkepaul make the final call. Would be good to see the related toast issue and who initially reported this:

> This was raised by developers through another toast issue, will link if I can find it but was quite a few mentions about it. I can only hope its for genuine reasons as It's unlikely for a user to complain about this type thing through our CMS feedback form. Personally I would like to move the top right tabs, because I know when testing with new users they don't look far right for things like settings.

**Comment by clarkepaul** [comment]
I've had a decent dig around in older issues but couldn't find mention of who and how often this was requested. It was never the main focus those issues it was mentioned in from memory, but more of a followup on conversations had... stuff about moving the position to top middle of CMS, or bottom right. I'm personally all good to close this issue without the PR, if it comes up again we can dig this one up again. I agree with whats been said above.

**Comment by robbieaverill** [comment]
It's reasonably likely that this was raised by one of the Silverstripe team members, since the toast notifications being above the CMS tabs meant that Behat tests would often fail when trying to click on CMS tabs. I agree with @clarkepaul that if this is the only driver it's probably not worth changing.

**Pull request closed without merging**
