### PR TITLE
FIX overflow hidden from inactive chosen

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripeltd/product-issues/issues/630

### CODE REVIEW

**Comment by michalkleiner** [comment]
Why is the dist JS file being updated, do you know? Should it stay the same when only changing scss source file?

**Comment by emteknetnz** [comment]
User error :-)

**Comment by GuySartorelli** [comment]
@emteknetnz The change that's shown here for `vendor.js` is already present in this branch: https://github.com/silverstripe/silverstripe-admin/blob/1.12-release/client/src/bundles/vendor.js

Have you accidentally squashed the css change on top of an existing commit?

**Comment by emteknetnz** [comment]
Rather than try and rebase this again, I've just redone in https://github.com/silverstripe/silverstripe-admin/pull/1418

**Pull request closed without merging**
