### PR TITLE
Fix behat reauthenticate tests

### PR DESCRIPTION
**Pull request by dnsl48**
Fix wording and remove explicit await for the server response;
From now onward we rely on the testsession:2.2 feature
allowing us to wait transparently for server to respond
after each step.

Requires:
 - [x] https://github.com/silverstripe/silverstripe-behat-extension/pull/185
 - [x] https://github.com/silverstripe/silverstripe-testsession/pull/58

### CODE REVIEW

**Comment by robbieaverill** [comment]
I've restarted the Behat builds since the dependent PRs are both merged now

**Comment by robbieaverill** [comment]
Still failing - Travis is installing stable versions of both dependencies, you'll need to tag a new release to get the changes here I guess. I'm not over the new changes so I'll leave it for your team =)

**Comment by maxime-rainville** [comment]
I've restarted the build. Merge on green :crossed_fingers:

**Comment by dnsl48** [comment]
Eh, we'll need to update `recipe-testing` as well. Good news, Guy has already done that in his PR - https://github.com/silverstripe/recipe-testing/pull/2

**Comment by dnsl48** [comment]
Here we go - https://github.com/silverstripe/recipe-testing/pull/3
(couldn't push into creative-commoners repo to update Guy's PR, so I created a new one)

**Comment by dnsl48** [comment]
Even though it's green, it's not because of the fix. 
Before merging this we still need to address https://github.com/silverstripe/recipe-testing/pull/3.

This particular build is green only by an accident. It is still failing on the original source branch - https://travis-ci.org/open-sausages/silverstripe-admin/builds/477146717

**Pull request merged**
