### PR TITLE
FIX Correctly close spans for btn loading icon

### PR DESCRIPTION
**Pull request by GuySartorelli**
The self-closing span tags were being incorrectly interpreted as _nested_ spans, instead of sibling spans. This is most likely a result of the recent update of jQuery.

The correct HTML syntax for these is to _not_ have them self-closing.

## Parent issue
- https://github.com/silverstripe/silverstripe-admin/issues/1426

### CODE REVIEW

**Comment by GuySartorelli** [comment]
Note: The JS job will likely fail due to https://github.com/silverstripe/silverstripe-admin/issues/1411 and https://github.com/silverstripe/silverstripe-admin/issues/1421, which is expected and should not block this PR from being merged.

**Review by michalkleiner — APPROVED** [review]
Looks ok, merge when you're happy with the tests, not sure if the failures are related or not. The change is fine on its own.

**Comment by GuySartorelli** [comment]
Rebased and rebuilt js - the actual change is unaltered.

**Review by lozcalver — APPROVED** [review]

**Comment by lozcalver** [comment]
> Running git diff
git diff found modified files when it should not have:
M js/bundle.js

Do we block merge for that? If not, feel free to self merge @GuySartorelli

**Comment by GuySartorelli** [comment]
We do, yeah. It means that when CI runs `yarn build` it's not getting the same results I got - in a community PR I'd be concerned they're trying to add something sneaky in there. In this PR I'm not sure what's causing it, but it's something that definitely needs resolving before we can merge.

**Comment by maxime-rainville** [comment]
@kinglozzer An attacker could try to build a bundle that doesn't match the PR and sneak a backdoor in the bundle.

**Comment by maxime-rainville** [comment]
I'm 90% sure the failure is a glitch. I forced another build, which will hopefully fix this.

**Comment by lozcalver** [comment]
@GuySartorelli could you try rebuilding the bundle locally? CI checks are still failing 😞

**Comment by GuySartorelli** [comment]
I have tried that already (I think? I can't see it in the PR history though..... maybe my memory is playing tricks) but will try again. We've had this problem once before with one of Steve's PRs, and when I created an identical PR to try to debug it my PR didn't have this problem.... so if it doesn't work this time I'll try opening a new PR (in draft initially just to see if it works) - and failing that I guess someone can build it locally and do a diff to validate that they get the same results I push up?
We'll see.

**Comment by GuySartorelli** [comment]
There was a change when I `yarn build`ed for some reason... not sure why but hopefully that fixes it.
Hurray for CI catching things yarn itself didn't.

**Comment by GuySartorelli** [comment]
This is finally green and already has two approvals. Self-merging.

**Comment by GuySartorelli** [comment]
@lekoala Released as [1.12.2](https://github.com/silverstripe/silverstripe-admin/releases/tag/1.12.2)

**Pull request merged**
