### PR TITLE
TreeDropdownField renders when being loaded without data through form loader 🐝

### PR DESCRIPTION
**Pull request by adrhumphreys**
This fixes an issue where the field is loaded through the FormLoader react component and therefore is initially passed props as `{ props: {}}` where the actual props are hidden inside so to access them you'd have to go `this.props.props`.

The easiest way to reproduce the issue is to create a page with the field and then use silverstripe-snapshot-admin to show a snapshotted version of the field which is the read only version

### CODE REVIEW

**Comment by robbieaverill** [comment]
Perhaps we need to fix the nested props object issue instead of disabling it while it loads?

**Comment by adrhumphreys** [comment]
Yeah this was very much a quick fix from our side, I think it still applies though as if this component is created without props then it will throw an exception and then nothing from the form loader will display

**Comment by robbieaverill** [comment]
I've rebased and built the dist files for you. I've also removed the emoji from your commit message (sorry!) - they are used in our changelogs, which may not necessarily support emojis, so we usually avoid using them

**Comment by robbieaverill** [comment]
I'm not sure, the Behat tests might be valid - any ideas?

**Comment by adrhumphreys** [comment]
Haven't a clue sorry, any way to view the travis artifacts?

**Comment by robbieaverill** [comment]
Not for pull request builds, unfortunately. I'll give this PR an actual test at some point

**Comment by robbieaverill** [comment]
The latest `1` branch build is green, so it could be a relevant failure

**Pull request closed without merging**
