### PR TITLE
FIX content block editing breaking when editing using IE11

### PR DESCRIPTION
**Pull request by bergice**
Fixes it by adding a Event constructor polyfill.

Resolves dnadesign/silverstripe-elemental#700
Resolves silverstripe/silverstripe-cms#2459

### CODE REVIEW

**Comment by maxime-rainville** [comment]
This sounds like this is something that would be worth fixing in all supported version. Do we want to back port it all the way back to 4.2 or 4.3?

**Comment by NightJar** [comment]
4.2 is out of support isn't it?

**Comment by maxime-rainville** [comment]
We still have a branch for it ... or have we decided to keep those around?

**Comment by robbieaverill** [comment]
I think it’s still in support. I was excluding it from Travis matrixes because it will probably get deleted soon

**Pull request merged**
