### PR TITLE
javascript i18n : lang attribute is set on html tag, not body

### PR DESCRIPTION
**Pull request by DrMartinGonzo**

### CODE REVIEW

**Comment by tractorcow** [comment]
Yes this seems correct. Example in https://www.w3.org/TR/html5/dom.html#elements-semantics shows this on the `<html>` tag also.

However this needs a rebase. I will merge this in manually.

**Comment by flamerohr** [comment]
I would like to extend it to fallback on the body element if the documentElement doesn't have a lang attribute :)

That way we could merge this into the `4.0` branch and then up all the way back to master

**Comment by tractorcow** [comment]
Sounds good.

**Comment by tractorcow** [comment]
I've rebased this and cleaned up the file at the same time https://github.com/silverstripe/silverstripe-admin/pull/458

**Pull request closed without merging**
