### PR TITLE
FIX: Show RightTitle on CheckboxField

### PR DESCRIPTION
**Pull request by sminnee**
RightTitle, if set, will be shown after Title
with a space between them.

Fixes https://github.com/silverstripe/silverstripe-framework/issues/3819

Also related: https://github.com/silverstripe/silverstripe-framework/pull/8898

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
I have a feeling that this will still not work in React context but I haven't tried it:

CheckboxField uses the `fieldHolder` HOC but with the `hideLabels` option...
https://github.com/silverstripe/silverstripe-admin/blob/5825958eafe63e6cf1ab88d7940ae1afe7865499/client/src/components/CheckboxField/CheckboxField.js#L14

The `hideLabels` option doesn't render a "right title"
https://github.com/silverstripe/silverstripe-admin/blob/65579ca6e12d784f85a2c46b13d6aa86074f983a/client/src/components/FieldHolder/FieldHolder.js#L114-L115

The code that generates the label for the checkbox doesn't consider the right title:
https://github.com/silverstripe/silverstripe-admin/blob/65579ca6e12d784f85a2c46b13d6aa86074f983a/client/src/components/OptionsetField/OptionField.js#L71-L73

**Comment by sminnee** [comment]
Confirmed

```php
$fields->push((new TextField('Test1', 'Left title'))->setRightTitle('Right title'));
$fields->push((new CheckboxField('Test2', 'Left title'))->setRightTitle('Right title'));
```

image

**Comment by sminnee** [comment]
How's this?

```diff
diff --git a/client/src/components/OptionsetField/OptionField.js b/client/src/components/OptionsetField/OptionField.js
index 4b0aeaa..35223df 100644
--- a/client/src/components/OptionsetField/OptionField.js
+++ b/client/src/components/OptionsetField/OptionField.js
@@ -68,10 +68,14 @@ class OptionField extends Component {
   }
 
   render() {
-    const labelText = this.props.leftTitle !== null
+    const leftTitle = this.props.leftTitle !== null
       ? this.props.leftTitle
       : this.props.title;
 
+    const labelText = this.props.rightTitle !== null
+      ? leftTitle + ' ' + this.props.rightTitle
+      : leftTitle;
+
     return (
       <FormGroup check>
         <Label check>
```

**Comment by sminnee** [comment]
And this is the result, which is the same as the other forms
image

**Comment by ScopeyNZ** [comment]
> How's this?

That's pretty much line for line how I would've done it 😉

**Pull request merged**
