### PR TITLE
FIX / TreeDropdownField empty value to be null

### PR DESCRIPTION
**Pull request by dnsl48**
The PR removes the legacy implementation of empty values for the component.
It used to be a string "unchanged" for multiselect field and a 0 for a single value.
However, we should avoid making such assumptions so that option id may be a string
in the future (e.g. uuid) as well as the word "unchanged" must not have any special meaning.

Related github issues:
 - silverstripe-assets/#176
 - silverstripe-framework/#8596
 - silverstripe-framework/#8332
 - silverstripe-framework/#8672

## Requires
 - [ ] https://github.com/silverstripe/silverstripe-framework/pull/8672

### CODE REVIEW

**Comment by dnsl48** [comment]
I _think_ (that's my assumption, I didn't debug it) the behat tests broke because we have to merge silverstripe/silverstripe-framework#8672 first.

**Comment by ScopeyNZ** [comment]
> I _think_ (that's my assumption, I didn't debug it) the behat tests broke because we have to merge [silverstripe/silverstripe-framework#8672](https://github.com/silverstripe/silverstripe-framework/pull/8672) first.

Yep working with dependant PRs can be frustrating. Often there's an "order" to merges. Sometimes you just have to say "I promise the builds are green when all the PRs are merged" and reviewers will have to check out locally to confirm.

**Comment by dnsl48** [comment]
In this particular case i think we can merge the first PR and then simply rerun the build for the second PR, wait it getting green and see :)

**Comment by robbieaverill** [comment]
Still red I'm afraid. Unsaved changes alert in Behat

**Comment by dnsl48** [comment]
Ok, just found out this PR is not the cause for the broken tests.
Here's the red build for the previous commit  https://travis-ci.org/open-sausages/silverstripe-admin

**Comment by dnsl48** [comment]
Ok, the test is broken because my fix for this issue, which was merged to `1.3` has not yet make it into master.
The fix for this behat issue is here - https://github.com/silverstripe/silverstripe-admin/pull/772

**Comment by dnsl48** [comment]
Haha, ok, now that's another one which I'm working on at the moment: #778

**Comment by maxime-rainville** [comment]
Failures are unrelated. Merging now.

**Pull request merged**
