### PR TITLE
Update chosen-js version in package.json

### PR DESCRIPTION
**Pull request by shoosah**
- This update fixes one of issues using `ListboxField` which would show the wrong suggestion(s) upon typing special characters like dollar sign, single quote, etc

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
I've noticed that you've created this pull request from one of the "core branches" rather than a branch specifically intended for this pull request. This can cause problems if we ask you to target this PR at a different branch. No action is needed at the moment, this is for your information.

In the future please create a new branch for each individual pull request. See our [guide about contributing PRs](https://docs.silverstripe.org/en/4/contributing/code/#step-by-step-from-forking-to-sending-the-pull-request).

**Comment by ScopeyNZ** [comment]
The builds haven't completed yet but I see that there's no dist files bundled with this PR. We have to (unfortunately) commit our dist files into our repo, so you need to ensure that you run a `yarn build` and add the `client/dist` bundles to your commit. The CI builds will fail if the bundle is not provided.

**Comment by shoosah** [comment]
Thanks @ScopeyNZ for your comments. There is no change after running `yarn build` for this PR and the CI build was successful (https://travis-ci.org/silverstripe/silverstripe-admin/builds/602077040).

**Comment by ScopeyNZ** [comment]
Hmmn. This fixed an issue for you too? If the dist files didn't change then how does this affect a live site?

**Comment by shoosah** [comment]
Yes, this was fixed in later versions of `chosen-js`. Since this has not been updated, I was getting errors using `ListboxField`. 
I use `$0-50` in my search filter which was using `ListboxField`. On typing `$` it shows the last character which is `0`. This behaviour was true for any text that starts with a special character.

**Comment by ScopeyNZ** [comment]
I see. One last thing I just realised - you can target this at the 1.4 branch as a bugfix for the 1.4.x line if you want. Just change the base branch in GitHub and then `git rebase HEAD~1 --onto upstream/1.4 && git push --force-with-lease`.

**Comment by shoosah** [comment]
Sure, I just did that @ScopeyNZ.

**Comment by shoosah** [comment]
Ping!

**Comment by ScopeyNZ** [comment]
I'm still really confused as to why this fixed any problem. The dist files aren't updated. But whatever, it's good to keep this stuff up to date.

**Pull request merged**
