### PR TITLE
ENH Remove GraphQL v3 compatability in mutation templates

### PR DESCRIPTION
**Pull request by GuySartorelli**
Following on from https://github.com/silverstripe/silverstripe-admin/pull/1498, removes the graphql v3 compatability for CMS 5

## Issue
- https://github.com/silverstripe/developer-docs/issues/62

### CODE REVIEW

**Review by sabina-talipova — CHANGES_REQUESTED** [review]
When I test this in my local I don't have any content in "Files" section, even Title and Breadcrumbs. If I switch to branch 2.0 all works fine.

**Comment by sabina-talipova** [comment]
Please, resolve conflict.
Thank you.

**Comment by GuySartorelli** [comment]
Rebased and conflict resolved. No issues in my local with assets admin after rebasing.

**Review by sabina-talipova — APPROVED** [review]
LGFM. Tested locally. Works fine.

**Pull request merged**
